### ISSUE TITLE
Is there anyway to make UITableViewHeaderFooterView work with it ?

### ISSUE THREAD

**Issue by jokefaker** [wczekalski/WCFastCell#9]
I have a tableview with both cell and section , what need I do if I want it work for UITableViewHeaderFooterView?

**Comment by wczekalski** [comment]
@jokefaker it reaquires some refactorings. Namely, you'd have to separate out the logic from `UITableViewCell` subclass and put it in a new utility class. Then create a subclass of `UITableViewHeaderFooterView ` which uses the utility class.
